# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  # pull_request:
  # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i
      working-directory: ./ng
    - name: Build application
      working-directory: ./ng
      run: npm run build --if-present
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: deploy # The branch the action should deploy to.
        folder: ng/dist/ng # The folder the action should deploy.
#     - name: Save to dist
#       uses: actions/upload-artifact@v2
#       with:
#         name: dist
#         path: |
#           dist
#           ng/dist
    # - run: npm test
